hello/urls.py
from django.urls import path
from . import views   #from currnet directory(app- hello) import views

urlpatterns=[
    path("index",views.index, name="index") , # search for httl://127:0:0:1/hello  as in hello folder & co related in main projct url   #name is included to esily reference from other parts of application 
    path("<str:name>/<str:branch>", views.greet,name='greet'),
    path("brian/",views.brian, name="brian") # search for http://127.0.0.1:8000/hello/brian to get this
] 

newyear/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path("",views.index,name="date")
]

tasks/urls.py
from django.urls import path

from . import views

app_name="tasks" # namespacing  # it help uniqy identify taskss as index can be of other appss also
urlpatterns =[
    path("",views.index,name="index"),
    path("add",views.add,name="add_new_tasks")
]

tode/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls")),
]

hello/models.py
from django.db import models

# Create your models here.

newyear/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.

# def anyone(request,name):
#     return HttpResponse(f"hello {name}  !!") #'f'. F-strings allow you to embed expressions inside string literals, using curly braces {} to enclose the expressions.


def index(request):
    return render(request,"hello/index.html")

def brian(request):
    return HttpResponse("hello brian")

def greet(request,name,branch): # taking name as an argument
    return render(request,"hello/greet.html",{
        "name":name.capitalize(),
        "bc":branch
        
    })

newyear/views.py
from django.shortcuts import render
import datetime


# Create your views here.

def index(request):
    today= datetime.datetime.now()

    return render(request,'newyear/index.html',{
        'newyear':today.month==1 and now.day==1
     })

tasks/views.py
from django.shortcuts import render

# Create your views here.

tasks=["learn","code","run"]

def index(request):
    return render(request,"tasks/index.html",{
             "tasks":tasks
    })

def add(request):
    return render(request,"tasks/add.html")
        
        
         
#when django is renderd , HTML teplate will access by , so django has acces to 
#to left side variable name tasks, taht has the value on the right 
#this value tasks take the value of above variable tasks

hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Web Page</title>
</head>
<body>

    <h1>Hello, {{name}} from {{bc}}</h1>
    

</body>
</html>

hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Web Page</title>
</head>
<body>

    <h1>Hello, World!</h1>
    <p>This is a simple HTML boilerplate template.</p>

</body>
</html>

newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>New Year Greetings</title>
<link href="{% static 'newyear/styles.css' %}" rel="stylesheet">
    
    
</head>
<body>
   
{% if today %}
     <h1>YES</h1>
{% else %}
     <h1>no</h1>
{% endif %}

</body>
</html>

tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block bodys %}


<form action="{ % url 'tasks:add_new_tasks % }" method="post">
<input type="text" name="task">
<input type ="submit">  
</form>

<a href="{% url 'tasks:index' %}" >see the task </a>

{% endblock %}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% comment %} template inheritance {% endcomment %}
{% block bodys %}


<ul>
{% for i in tasks%}
<li>{{i}}</li>
{% endfor%}
</ul>

{% comment %} link to url called add_new_tasks , We wrote name="add_new_tasks" {% endcomment %}
<a href="{% url 'tasks:add_new_tasks' %}">Add neww tasksss</a> 

{% endblock %}

    

tasks/templates/tasks/layout.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Taskss</title>
<link href="{% static 'newyear/styles.css' %}" rel="stylesheet">
<h1>tasks</h1>  
</head>



<body>
   {% block bodys %}
   {% endblock %}
</body>



</html>